### ISSUE TITLE
Atom v185.0以降で動かない

### ISSUE THREAD

**Issue by hokaccha** [raccy/japanese-wrap#2]
このコミットで`DisplayBuffer#findWrapColumn`が`TokenizedLine#findWrapColumn`に移動したのが原因で動かなくなっているようです。（このコミットはv185.0に含まれています）
https://github.com/atom/atom/commit/62434d9ad55baf137f30d34d68c13553d0eb2afe

直そうと思ったんですが、`TokenizedLine#findWrapColumn`を書き換えるのが大変そうだったので、ひとまず報告だけしておきます。

**Comment by hokaccha** [comment]
とりあえず無理やりprototypeをたどって書き換えてみて動いてはいるんですが、どうなんでしょうか・・。
https://github.com/hokaccha/japanese-wrap/commit/7f5548e38cc080f5560ba0a379c7baf564047437

**Comment by raccy** [comment]
詳しい情報ありがとうございます。修正版リリースしましたので、アップデートしてみて下さい。

ご指摘のパッチの通り、`TokenizedLine`のオブジェクトが随時作成になるので、以前のバージョンのようなオブジェクトの特異メソッドではなく、クラスのインスタンスメソッドをハックする必要がありました(特異メソッドとかインスタンスメソッドってそれ、Rubyの表現じゃ)。
`TokenizedLine`のクラス自体を`construcotr::`で取るか`__proto__`で取るか悩みましたが、短い方を選びました。(Rubyだと`Object#class`ってメソッドがあるのに、なぜCoffeeScriptにないんだ！)
不安は`DisplayBuffer`の`@tokenizedBuffer`くんが一個も`TokenizedLine`を持っていない(`@tokenizedLines`が空)場合でしたけど、新規ファイルも必ず一行できるので、大丈夫のようです。一応、取れなかったときはログだけ出して、諦めました。

**Comment by hokaccha** [comment]
なるほど、ありがとうございます！
