### ISSUE TITLE
特定の文字列を含むファイルを開くと Atom がフリーズしてしまう

### ISSUE THREAD

**Issue by firisu** [raccy/japanese-wrap#5]
### バージョン等
* Atom 0.189.0, japanese-wrap 0.2.5, Mac OS 10.9
* Atom 0.190.0, japanese-wrap 0.2.5, Windows 7

にて再現。

テストはしていませんが Atom 0.184.0 までは
発生していなかったと思います。

### 現象
```
  ・
```

```
  」
```

```
	・
```

上記のようなテキストだけのファイルを開くと Atom がフリーズします。

分かりにくいので補足すると、上から

1. 半角スペース2つ、中黒
2. 半角スペース2つ、閉じ括弧
3. 水平タブ、中黒

です。

### 補足
* 上記の文言が行頭から記述されている場合のみフリーズするようです。（文中の時は問題なし）
* タブや空白がない場合、半角スペースが3つの場合などはフリーズしません。
* 「日本語禁則処理を行なう」をオフにするとフリーズしません。

**Comment by raccy** [comment]
私の環境でも現象が確認できました。
かなり謎な動きですが、調査しますので、しばらくお待ち下さい。

**Comment by raccy** [comment]
対応版0.2.6をリリースしたので、アップデートしてみて下さい。

どうやら、最初の読込で幅"0"で行に入る文字数を求める事があるようで、
特定の文字列だと、無限ループにはまり、フリーズ状態となっていました。
幅"0"だと計算せずに、返すように変更しました。

**Comment by firisu** [comment]
Atom 0.190.0, japanese-wrap 0.2.6, Mac OS 10.9
にて試しましたが、まだフリーズしてしまいます。
念のためパッケージの再インストールも試しましたが変わりませんでした。

**Comment by raccy** [comment]
なんか、うまく直っていなかったようです。再度対応しますので、お待ち下さい。

**Comment by raccy** [comment]
対応版0.2.7をリリースしました。今度こそ直っているはず。

どうやら、「Sofw Wrap At Preferred Line Length」の有効無効によって、
0の場合とnullの場合の2パターンがあったようです。
手元の環境では有効にしたときの0のパターンだけしか試してなかったので、
nullの場合の確認が漏れてました。
とりあえず、null値やundefined値チェックを入れたので、
これで無限ループはしないようになると思います。

**Comment by firisu** [comment]
0.2.7 確認しました。
フリーズしなくなっていました。

対応ありがとうございました！
