### ISSUE TITLE
1.0リリース後のこのパッケージについて

### ISSUE THREAD

**Issue by raccy** [raccy/japanese-wrap#8]
READMEにも記載していますが、CJKなどアルファベット以外でのソフトラップが
うまく動かない問題は1.0リリースまでのロードマップに含まれていました。
そのため、このパッケージは1.0未満対応とパッケージ情報には記載しており、
1.0以上ではインストール時に警告が表示されるようになっているはずです。

しかし、ご存じの通り残念ながら1.0には間に合いませんでした。
かといって今後対応しないわけでは無く、現在対応に向けて開発中のようです。

ひとまず、知らない人もいるかと思いますので、私の知る限りの今までの流れと現状を報告します。
英語がわかるかたは本家のIssues等を読んでいったほうが早いので、英語版の説明はありません。

1. Atom本家のIssuesでCJKがうまくラップされないという報告がある。
2. japanese-wrapを参考にしていろいろすればいいんじゃね？と話になる。
    (というか、この頃はまだ、本家のIssuesで知らない間に話題になっているのを知らんかった)
3. 日本語とモノスペースフォントしか対応してないから、もっと工夫が必要という話になる。
4. @SaschaNaz さんが measureText を使うアイデアを出して、実際forkしてパッケージ作る。
5. @SaschaNaz さんが Atom のパッチ作ってプルリクする。
6. テキスト周りは text-document ってやつで作り直しているから、そっちにしてくれとなる。
7. 俺が text-document のパッチ作ってプルリクする。
8. text-document がうまくいかなかったので、text-document 自体無くなる。
9. @SaschaNaz さんと俺は途方に暮れる＞＜
10. @nathansobo さんが事情を説明する。
    * CJK等のアルファベット以外の文字についてもちゃんと対応する予定はある。
    * 現在、文字の幅を計る仕組みを作っている最中で、measureTextではなく、そっちを使って実装する予定になっている。
    * ただ、パフォーマンスを落とさずに文字の幅を計ることがなかなか実現できていなく、時間がかかっている。

たぶん、こんな感じです。
で、今まさしく、文字幅計算の実装にとりかかっているところとなっています。
本家の対応がいつ頃できるかはわかりませんが、このパッケージについては、
しばらく現状維持としたいと思います。

**Comment by tomoya** [comment]
詳しい説明ありがとうございます。とても参考になりました。
僕が追っている情報とも、ほとんど相違がないので安心しました。

ご覧になっている他の方のために情報を追加しておくと、
上で説明は、それぞれ次の issues で行なわれている話になっています。

- [Atom doesn't soft wrap CJK(Chinese/Japanese/Korean) correctly #1783](https://github.com/atom/atom/issues/1783)
- [New text wrapper, measuring actual text widths #6425](https://github.com/atom/atom/pull/6425)
- [Soft wrap for CJK #14](https://github.com/atom/text-document/pull/14)
- [Char measurement #6083](https://github.com/atom/atom/pull/6083)

個人的には、Char meaturement も結構難航しているので、現状ではいつ取り込まれるかまったく先が見えない感じで少し不安ですね。

**Comment by raccy** [comment]
ワードラップ周りについて、Atom 1.1.0からCJK文字の幅を考慮するようになりましたが、改行ルールについてはまだ問題があるようです。
[Provide different soft-wrapping rules for CJK languages #9447](https://github.com/atom/atom/issues/9447)
このパッケージは引き続きこのままで残しておきます。

なお、プロポーショナルフォントとかはまだまだ無理っぽいです。俺はプロポーショナルフォントを使いたいんじゃーって方のために、パッケージを自分用に作りました。
[wrap-style](https://atom.io/packages/wrap-style)
なお、結構重いです。大きなファイルを開くときはちょっと固まるぐらいを覚悟してから使ってください。速度の改善方法は随時募集中です！

**Comment by griffin-stewie** [comment]
[Atom 1.2](http://blog.atom.io/2015/11/12/atom-1-2.html "Atom 1.2")
上記ブログで CJK Soft Wrap には対応されたみたいですね。
私の環境で本Packageを外したら綺麗に Soft Wrap されていました。

@raccy  さんありがとうございました。

**Comment by raccy** [comment]
遅くなりましたが、たぶん、そろそろAtom本家も落ちついたような気がするので、このパッケージについては、1.2.0以降のAtomで無効となり、メッセージを出すようにしました。

等幅フォントを使用しているときのラップの問題は本家の方で対応していった方がいいと思いますので、このパッケージで何とかしようというのはやらない予定です。プロポーショナルフォントについては、稚拙な出来の[wrap-style](https://atom.io/packages/wrap-style)で続けていこうとは思っています。

これまでのご愛用ありがとうございました。

**Comment by tomoya** [comment]
:+1:

**Comment by griffin-stewie** [comment]
:+1:
