### ISSUE TITLE
改行される文字数が各行でバラバラになってしまいます。

### ISSUE THREAD

**Issue by tarky** [raccy/japanese-wrap#9]
![2015-11-18 11 27 20](https://cloud.githubusercontent.com/assets/3303297/11230961/63688d22-8de7-11e5-9292-e63462829778.png)

本日使い始めたのですが、画像のように改行される文字数が揃いません。
こちらの環境は以下のような感じです。何か設定が足りていないのでしょうか。教えて頂けたら幸いです。ちなみに、「Soft Wrap At Preferred Line Length」はONとOFF両方試しましたが、同じように文字数が揃いませんでした。

項目 | 内容
------------ | -------------
OS | OS X 10.10.5
Atomバージョン | 1.2.1
japanese-wrapのバージョン |  0.2.10
Preferred Line Length | Defaultのまま
Soft Wrap | ON
Soft Wrap At Preferred Line Length | ONとOFF両方試しました

**Comment by chibicode** [comment]
1.2.0のChangelogに"Soft-wrapping now works correctly with a larger variety of non-Latin characters, including CJK."とありますが、1.2.0以降はもうこのパッケージは必要がないのかもしれません。アンインストールしても問題ありませんでした。
https://github.com/atom/atom/releases/tag/v1.2.0

**Comment by tarky** [comment]
わざわざ回答ありがとうございます。了解しました。atomにあるsoft wrapを使います。こっちも微妙な挙動ですが。
